### ISSUE TITLE
Can't Record Stories

### ISSUE THREAD

**Issue by MrDogeBro** [benawad/vscode-stories#15]
Whenever I try to record a story I get the error `Cannot read property 'width' of undefined`. Any clue why this is or how to fix it?
![Screen Shot 2020-10-30 at 2 40 55 PM](https://user-images.githubusercontent.com/35872177/97744701-14341c80-1abe-11eb-803b-ea3b7608d528.png)

### Details
OS: `Mac`
Date: `10/30/20`
VSC: `1.50.1`

**Comment by ViNoS-ab** [comment]
check if your code has errors

**Comment by hipniusF** [comment]
Do you have ffmpeg install?

**Comment by MrDogeBro** [comment]
Yes — I had a second VSCode window open, don't know if that was causing the issue or not but it's working now.
