### ISSUE TITLE
Suggestion : Using regex to not allow NSFW usernames

### ISSUE THREAD

**Issue by HariAcidReign** [benawad/vscode-stories#22]
Is this an issue that needs addressing? Right now the names seem to be combinations of animals, colors, etc but will this suffice when say, a friend request feature, or search people based on username feature is added?

PS: I would like to work on this feature if its viable

**Comment by CallmeHongmaybe** [comment]
Yo good suggestion

**Comment by benawad** [comment]
@HariAcidReign go for it

**Comment by YashMunjal** [comment]
Sorry but I wanna help regarding the NSFW content @benawad. I am kinda lost but just wanna ask that is this capture the screen at the time or the keystrokes while the stories are being recorded?

**Comment by stemount** [comment]
@HariAcidReign @YashMunjal have a look and open a PR but this issue should be API side. https://github.com/benawad/vscode-stories-api/issues/7

**Comment by benawad** [comment]
https://github.com/benawad/vscode-stories-api/issues/7#issuecomment-720120604
