### ISSUE TITLE
Suggestion: Add more language flairs

### ISSUE THREAD

**Issue by arnav03mehta** [benawad/vscode-stories#35]
Add more language flairs like python, go, cpp, java, etc.

**Comment by YazeedAlKhalaf** [comment]
I have made a PR for Flutter, Will do other languages 🚀

**Comment by arnav03mehta** [comment]
I'm adding the python and java flairs now and wanted some suggestions about what I should put in their descriptions.

**Comment by arnav03mehta** [comment]
i'm currently on "for the snake lovers" for python and "if you like coffee" for java,

**Comment by YazeedAlKhalaf** [comment]
this pull request [https://github.com/benawad/vscode-stories/pull/44](https://github.com/benawad/vscode-stories/pull/44) is related to this issue. Can you suggest new languages there?

**Comment by arnav03mehta** [comment]
added 2 more flairs in #45 (golang and cpp)

**Comment by TheFern2** [comment]
This might be a dumb question haha, what in the world is flair?
