### ISSUE TITLE
Suggestion: How to fix nsfw issues and improve the extension overall 

### ISSUE THREAD

**Issue by TheFern2** [benawad/vscode-stories#38]
I think trying to fight nsfw with vision apis and whatever other plugins is going to be a forever fight, and quite frankly not worth it given that code is text based anyways.

I suggest you switch to text file based stories. Select a piece of code then upload story, via a extension command. The file might need some restriction based on file size, or how many characters, etc, so people don't upload huge files.

The people viewing the stories can easily scroll through the story and if they see a piece of code they like they can copy it. Story maker can restrict copy and paste if they choose to.

**Comment by benawad** [comment]
agreed, do you think we need to worry about inappropriate ascii art?

**Comment by TheFern2** [comment]
I didn't even think about ascii art tbh, yes that's another concern. Though ascii art should be relatively easier to spot as is usually sequentially random letters, same letters, and/or white space. If anyone is coding like that I'll be more worried.

**Comment by TheFern2** [comment]
Could also add an option for automatic scrolling to give the feeling of a story video.

**Comment by hyperloop11** [comment]
I had a suggestion in this regard, you could train a ML classification model on different vs code themes. It could figure out which stories are from vs code and which are not, then publish only those stories which are vs code screen recordings. This will not fix inappropriate ascii art problem, though.

**Comment by hyperloop11** [comment]
I had a suggestion in this regard, you could train a ML classification model on different vs code themes. It could figure out which stories are from vs code and which are not, then publish only those stories which are vscode screen recordings.

**Comment by Bobj2018** [comment]
Yes, I agree, something needs to be done 🤔. I was looking forward to see projects people are working on but instead, the top post was a warning about some troll posting NSFW content. There are other images too, like a chicken nugget?

**Comment by TheFern2** [comment]
@hyperloop11 It doesn't really matter much if you do ML for vscode themes. You can preview an image on vscode and that image can be anything. I bet people can even figure out how to have vscode in the background and a porn video in the front overlayed. That would trick the ML that it is vscode related, no?

**Comment by Dezzmeister** [comment]
The text stories are boring. I suggest you go back to gifs and run a neural network on the backend to reject any stories that have porn. I'm pretty sure there are some open source networks like this, so you wouldn't have to train one yourself.

I would be willing to develop this feature but I simply don't have the time.

**Comment by TheFern2** [comment]
@Dezzmeister No matter what you do, people will find ways around it. It isn't worth spending tons of hours fighting porn.

**Comment by Dezzmeister** [comment]
> 
> 
> @Dezzmeister No matter what you do, people will find ways around it. It isn't worth spending tons of hours fighting porn.

No need to spend too much time on it. The neural network can catch most of the blatant violations, and there can be a 'report' feature for anything that slips through the cracks.

**Comment by TheFern2** [comment]
> > @Dezzmeister No matter what you do, people will find ways around it. It isn't worth spending tons of hours fighting porn.
> 
> No need to spend too much time on it. The neural network can catch most of the blatant violations, and there can be a 'report' feature for anything that slips through the cracks.

Perhaps in the future ML can be tested on the dev branch and you can have the ability for sharing both text based, and gif. With that being said text based offer a great advantage over gifs, is that if you see a piece of code you like or think is cool you can copy. Can't do that with gifs. Anyways closing this. if you can submit PR for ML that would be great, it isn't my field of work.

**Comment by Dezzmeister** [comment]
> 
> 
> > > @Dezzmeister No matter what you do, people will find ways around it. It isn't worth spending tons of hours fighting porn.
> > 
> > 
> > No need to spend too much time on it. The neural network can catch most of the blatant violations, and there can be a 'report' feature for anything that slips through the cracks.
> 
> Perhaps in the future ML can be tested on the dev branch and you can have the ability for sharing both text based, and gif. With that being said text based offer a great advantage over gifs, is that if you see a piece of code you like or think is cool you can copy. Can't do that with gifs. Anyways closing this. if you can submit PR for ML that would be great, it isn't my field of work.

I'll work on it
