### ISSUE TITLE
Suggestion: Asciinema style recording

### ISSUE THREAD

**Issue by Merlin04** [benawad/vscode-stories#57]
It would be neat if stories could be recorded still but only by typing text into a file (the extension would monitor the key presses and see at what time they were pressed), and it is converted to a GIF and played back (or by updating the content of the current file).

**Comment by FluentCoding** [comment]
That's what I've also thought. We could e.g. record every single cursor movement and every file addition and play it afterwards.

**Comment by benawad** [comment]
tried it, but I think I like gif better
