### ISSUE TITLE
not worky 💩

### ISSUE THREAD

**Issue by RemiKalbe** [benawad/vscode-stories#6]
bipbip boopboop
![image](https://user-images.githubusercontent.com/8604600/97722701-397b5780-1acb-11eb-8c54-710728663d03.png)

**Comment by GiancarlosIO** [comment]
same here :(

**Comment by samuelbarata** [comment]
Duplicate of #5

**Comment by daviesesiro** [comment]
I think his credits has finished on azure😞😞

**Comment by RemiKalbe** [comment]
![image](https://user-images.githubusercontent.com/8604600/97723474-1ef5ae00-1acc-11eb-8d0c-9a9ba5ce18d1.png)

**Comment by RemiKalbe** [comment]
![image](https://user-images.githubusercontent.com/8604600/97723487-24eb8f00-1acc-11eb-8d54-757e92c7e192.png)

**Comment by SeksayMan** [comment]
https://github.com/benawad/vscode-stories/issues/5#issuecomment-719611491

**Comment by SibiAkkash** [comment]
Ahh, that's why

**Comment by ViNoS-ab** [comment]
oh i see why

**Comment by canicjusz** [comment]
knew this would happen.

**Comment by RemiKalbe** [comment]
it worky 😍

**Comment by mrbinary71** [comment]
I have CORS error !!
An error has occured: Failed to fetch!!

OS: Ubuntu
Stories Ext Version: 2.22.1
VSC Version: 1.52.1

**Comment by TheFern2** [comment]
> I have CORS error !!
> An error has occured: Failed to fetch!!
> 
> OS: Ubuntu
> Stories Ext Version: 2.22.1
> VSC Version: 1.52.1

Please open a new issue, where are you seeing a CORS error?
