### ISSUE TITLE
Stories not loading and commands not found

### ISSUE THREAD

**Issue by spyronsk95** [benawad/vscode-stories#70]
I've tried stories on vscodium, where it was not working. It was loading forever. Also when I want to refresh the stories, it prompts me: "command 'stories.refresh' not found. Same for any other storie related command.

VSCodium and VSCode newest version, OS Ubuntu 20.04

Thought mabye it's VSCodium related. But same happens on VSCode.

E:

Okay, i switched between plugin versions. The last version which is working for me is 2.4.0. Higher versions are all broken. But storie uploading is taking forever/not working.

**Comment by bar9** [comment]
If you rename ~/.vscode/extensions/benawad.stories/Playback.js to lowercase playback.js, it works. I assume this works on a mac (and for the majority of users) because of the case-insensitive file system of mac.
I'll try and follow up with a PR.

**Comment by JackQAQ-byte** [comment]
@bar9 's method work on linux as well (Manjaro), thanks! :100:

**Comment by benawad** [comment]
I just published a new version with that file renamed which I think should fix it.
