### ISSUE TITLE
Adrianjg NSFW ascii image

### ISSUE THREAD

**Issue by TheFern2** [benawad/vscode-stories#77]
Got user in title with ascii image, I guess people just can't help themselves. I'd rather not paste pic here.
Might want to start blocking github users so at least there is some repercussions.

I believe this user is this one @adrianjgil

**Comment by benawad** [comment]
I hardcoded the id to ban for now, but will probably need to add a system for this

**Comment by TheFern2** [comment]
This reminds me, I will work on a npm package to detect ascii art sometime this weekend.

**Comment by TheFern2** [comment]
> I hardcoded the id to ban for now, but will probably need to add a system for this

Also not sure what information you get with github auth, but users can change github username, so not sure if the ban can be tied to something more precise like email/s or some other user github uuid. Just a few thoughts.
