### ISSUE TITLE
Can't get into Settings

### ISSUE THREAD

**Issue by duhan2** [benawad/vscode-stories#81]
I installed the extension and wanted to configure the settings.
When I opened the VSCode settings and searched for "Stories", it could not find the extension "Stories" in the Settings.
So I am not able to configure the extension.
Reinstalling did not fix the problem either.

**Comment by benawad** [comment]
There is no longer any settings

**Comment by duhan2** [comment]
Thank You

**Comment by WarenGonzaga** [comment]
@benawad how to login? or use the stories?

**Comment by benawad** [comment]
@WarenGonzaga when you press record story it'll prompt you

Check the readme on how to view the stories

**Comment by WarenGonzaga** [comment]
@benawad got it! You may now close this hehe
